{'A.E., E.P.E., O.E., E.E., I.K.E.',
 'A.Ş., Ltd. Şti., Komandit Şti., Kolektif Şti.',
 'AB, HB, KB, EF',
 'AG, GmbH, Sarl, Sàrl, KG, Cooperative',
 'AS, ASA, ANS, DA, Enkeltpersonforetak',
 'ApS, A/S, IVS, P/S',
 'BV, NV, VOF, CV, Stichting',
 'CA, SRL, SA, SC',
 'Co., Ltd., PLC, LP, LLP',
 'Corp., Inc., Partnership, Cooperative',
 'Corporation, Inc.',
 'DOOEL, AD',
 'EURL, SARL',
 'Ehf., Hf., Slf.',
 'GmbH, AG, KG, OHG, GmbH & Co. KG',
 'GmbH, AG, OG, KG',
 'Inc., Ltd., PLC, Pvt Ltd., Ltd.',
 'JSC, LLC',
 'JSC, LLC, Ltd., Partnership',
 'KK, GK, YK, Kabushiki Kaisha, Gōdō Kaisha',
 'Kft., Rt., Bt., Kkt.',
 'LDA, S.A.',
 'LDA, SARL',
 'LLC, Inc., Corp., LP, LLP, PC, PLLC',
 'LLC, JSC',
 'LLC, JSC, PE, Partnership',
 'LLC, JSC, SPC',
 'LLC, OJSC',
 'LLC, OJSC, CJSC, Partnership',
 'LLC, PSC, FZE, FZC, PJSC, PrJSC',
 'LLC, PSC, PLC',
 'LLC, S.A.',
 'LLC, SAOC, SPC',
 'LLP, JSC, PE, SP, Sh.a., Sh.p.k.',
 'LTDA, SA, EIRELI, MEI',
 'LTDA, SA, EIRL, SpA',
 'Lda, SA, SCR, SGPS',
 'Lda, SARL',
 'Ltd, PLC, LLP, LP, CIC',
 'Ltd., Co., CJSC, OJSC, LLC',
 'Ltd., Co., LLC, JV',
 'Ltd., Co., WFOE, JV, Rep. Office',
 'Ltd., Corp.',
 'Ltd., Inc.',
 'Ltd., Inc., Corp., ULC, LP, LLP',
 'Ltd., Inc., Partnership, Cooperative',
 'Ltd., LLC',
 'Ltd., LLC, Partnership',
 'Ltd., LLP, Inc.',
 'Ltd., LP, Incorporated Society, Charitable Trust',
 'Ltd., PLC',
 'Ltd., PLC, DAC, CLG, ULC',
 'Ltd., PLC, LLC',
 'Ltd., PLC, LLP, Cooperative',
 'Ltd., PLC, Pvt Ltd.',
 'Ltd., PLC, SACCO',
 'Ltd., PLC, Unltd.',
 'Ltd., PSC, Pvt Ltd.',
 'Ltd., Plc, LLC',
 'Ltd., Plc, Unlimited, Ltd./Gte.',
 'Ltd., Pty Ltd. , Inc.',
 'Ltd., Pty Ltd., Inc.',
 'Ltd., Pvt Ltd, Partnership',
 'Ltd., Pvt Ltd.',
 'Ltd., S.A.',
 'NV, BV, CV, SCRL, Comm. V.',
 'OOD, AD, EOOD, EAD',
 'OOO, AO, IP, PAO',
 'OOO, OAO, ZAO, UP',
 'OOO, ZAO',
 'Oy, Oyj, Ky, Ay, Osk',
 'OÜ, AS, UÜ',
 'PLC, SC, PE',
 'PT, CV, Firma, Perusahaan Perseorangan',
 'PTY Ltd., BWP, ',
 'Pte Ltd, Ltd., LLP, LP',
 'Pte Ltd., Ltd., FJ, PLC',
 'Pty Ltd, Limited, NL, Inc., Trust, Unit Trust, Partnership',
 'Pty Ltd, Ltd., CC, NPC, Sole Proprietor',
 'Pty Ltd., Ltd.',
 'Pvt Ltd, LLP, Ltd., OPC, Partnership',
 'Pvt Ltd, Ltd., Partnership, LLP',
 'Pvt Ltd, Ltd., Partnership, LLP, S.A.R.L.',
 'Pvt Ltd, PLC, LLP, Unlimited Company',
 'Pvt Ltd, Public Ltd., JV, S.A., Ltd.',
 'Pvt Ltd., Ltd.',
 'Pvt. Ltd., PLC',
 'Q.P.S.C., LLC, SPC',
 'S.A.',
 'S.A. de C.V., S. de R.L. de C.V., SAPI de C.V., SA',
 'S.A. de C.V., S.R.L.',
 'S.A.,',
 'S.A., Cía. Ltda., SARL',
 'S.A., EURL',
 'S.A., Ltd.',
 'S.A., S.R.L.',
 'S.A., S.R.L.,',
 'S.A., S.R.L., LLC',
 'S.A., S.à r.l.',
 'S.A., SARL',
 'S.A., SARL,',
 'S.A., SRL',
 'S.A., SRL, S.A.S., S.C., S.G.R.',
 'S.A.R.L',
 'S.A.R.L.',
 'S.A.R.L.,',
 'S.A.R.L., LLC',
 'S.A.R.L., S.A.',
 'S.R.L., C.L.',
 'SAC, SRL, SA, EIRL',
 'SAE, LLC, JV, Ltd., Sole Proprietorship',
 'SAL, SARL, SNC',
 'SARL, EURL',
 'SARL, EURL,',
 'SARL, S.A.',
 'SARL, SA',
 'SARL, SA,',
 'SARL, SA, SCA',
 'SARL, SA, SCP',
 'SARL, SA, SNC',
 'SARL, SA, SNC, SCA',
 'SARL, SAM',
 'SARL, SAS, SASU, SA, SCI',
 'SAS, SA, LTDA, SCA',
 'SDN BHD, BHD',
 'SIA, AS',
 'SL, SA, SRL, SLL, SC',
 'SPA, SARL, EURL',
 'SRL, SA, EIRL',
 'SRL, SA, SNC',
 'SRL, SA, SNC, SCS, SCA',
 'SRL, SPA, SNC, SAS',
 'Sdn Bhd, Bhd, LLP, Sole Proprietor',
 'Sh.p.k., S.A., S.E.',
 'Sp. z o.o., S.A., Sp. j., Sp. k.',
 'TOV, AT, PT, DP',
 'UAB, AB',
 'W.L.L., B.S.C.',
 'WLL, KSCC, SPC',
 'd.o.o., A.D.',
 'd.o.o., AD',
 'd.o.o., a.d., k.d.',
 'd.o.o., d.d.',
 'd.o.o., d.d., j.d.o.o.',
 'd.o.o., d.d., k.d.',
 's.r.o., a.s.',
 's.r.o., a.s., v.o.s., k.s.'}
